---
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^main|master$/
      when: always
    - if: $CI_COMMIT_BRANCH =~ /^dev(elop)?(ment)??$/
      when: always
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^dev(elop)?(ment)??$/
      when: always
stages:
  - version
  - build
  - push
  - config
get_version:
  image: 
    name: gittools/gitversion:5.12.0-alpine.3.14-6.0
    entrypoint: [""]
  variables:
    GIT_STRATEGY: fetch
    GIT_DEPTH: 0
    IGNORE_NORMALISATION_GIT_HEAD_MOVE: 1
  stage: version
  script:
    - /tools/dotnet-gitversion /nocache /nofetch /showvariable MajorMinorPatch > version.txt
    - /tools/dotnet-gitversion /nocache /nofetch /showvariable FullSemVer > fullSemVer.txt
    - /tools/dotnet-gitversion /nocache /nofetch /showvariable PreReleaseLabel > preReleaseLabel.txt
    - cat *.txt
  artifacts:
    paths:
      - "*.txt"
  only:
    refs:
      - main
      - dev
docker-build:
  image: docker:24.0.2-alpine3.18
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - | 
      if [[ $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH ]]; then
        TAG=$(cat version.txt)
        LABEL=""
      else
        TAG=$(cat fullSemVer.txt)
        LABEL=$(cat preReleaseLabel.txt)
      fi
    - docker build --pull -t "$CI_REGISTRY_IMAGE${TAG}" .
    - docker tag "$CI_REGISTRY_IMAGE${TAG}" "$CI_REGISTRY_IMAGE$LABEL"
    - docker tag "$CI_REGISTRY_IMAGE${TAG}" "$CI_REGISTRY_IMAGE$TAG"
    - docker push "$CI_REGISTRY_IMAGE:$LABEL}"
    - docker push "$CI_REGISTRY_IMAGE:$TAG}"
  needs:
    - job: get_version
      artifacts: true
  only:
    refs:
      - main
      - dev
config:
  stage: config
  needs:
    - job: docker-build
  image: 
    name: $CI_REGISTRY_IMAGE:latest
    entrypoint: [""]
  script:
    - "echo hello"
...