
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^main|master$/
      when: always
    - if: $CI_COMMIT_BRANCH =~ /^dev(elop)?(ment)??$/
      when: always
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^dev(elop)?(ment)??$/
      when: always
stages:
  - version
  - build
  - push

get_version:
  image: 
    name: gittools/gitversion:5.12.0-alpine.3.14-6.0
    entrypoint: [""]
  variables:
    GIT_STRATEGY: fetch
    GIT_DEPTH: 0
    IGNORE_NORMALISATION_GIT_HEAD_MOVE: 1
  stage: version
  script:
    - /tools/dotnet-gitversion /nocache /nofetch /showvariable MajorMinorPatch > version.txt
    - /tools/dotnet-gitversion /nocache /nofetch /showvariable FullSemVer > fullSemVer.txt
    - cat version.txt
    - cat fullSemVer.txt
  artifacts:
    paths:
      - version.txt
      - fullSemVer.txt

docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - longTag=$(cat fullSemVer.txt)
    - docker build -t "$CI_REGISTRY_IMAGE${longTag}" .

docker-push:
  image: docker:latest
  stage: push
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - longTag=$(cat fullSemVer.txt)    
    - docker push "$CI_REGISTRY_IMAGE:${longTag}"
  
docker-push-latest:
  image: docker:latest
  stage: push
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - tag=$(cat version.txt)
    - longTag=$(cat fullSemVer.txt)
    - docker tag "$CI_REGISTRY_IMAGE:${longTag}" "$CI_REGISTRY_IMAGE:${tag}"
    - docker tag "$CI_REGISTRY_IMAGE:${tag}" "$CI_REGISTRY_IMAGE:latest"
  only:
    - main
    - master