
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^main|master$/
      when: always
    - if: $CI_COMMIT_BRANCH =~ /^dev(elop)?(ment)??$/
      when: always
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^dev(elop)?(ment)??$/
      when: always
stages:
  - version
  - build
  - push

get_version:
  image: gitversion/gitversion:latest-linux
  stage: version
  script:
    - gitversion /output /nofetch /showvariable MajorMinorPatch > version.txt
    - cat version.txt
  artifacts:
    paths:
      - version.txt

docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - tag=$(cat version.txt)
    - docker build --pull -t "$CI_REGISTRY_IMAGE${tag}" -f dockerfile .

docker-push:
  image: docker:latest
  stage: push
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - tag=$(cat version.txt)
    - docker push "$CI_REGISTRY_IMAGE${tag}"
  
docker-push-latest:
  image: docker:latest
  stage: push
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - tag=$(cat version.txt)
    - docker tag "$CI_REGISTRY_IMAGE${tag}" "$CI_REGISTRY_IMAGE:latest"
  only:
    - main
    - master