---
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^main|master$/
      when: always
    - if: $CI_COMMIT_BRANCH =~ /^dev(elop)?(ment)??$/
      when: always
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^dev(elop)?(ment)??$/
      when: always
stages:
  - version
  - build
  - push
  - config
get_version:
  image: 
    name: gittools/gitversion:5.12.0-alpine.3.14-6.0
    entrypoint: [""]
  variables:
    GIT_STRATEGY: fetch
    GIT_DEPTH: 0
    IGNORE_NORMALISATION_GIT_HEAD_MOVE: 1
  stage: version
  script:
    - /tools/dotnet-gitversion /nocache /nofetch /showvariable MajorMinorPatch > version.txt
    - /tools/dotnet-gitversion /nocache /nofetch /showvariable FullSemVer > fullSemVer.txt
    - cat version.txt
    - cat fullSemVer.txt
  cache:
    key: ${CI_COMMIT_BRANCH}
    untracked: true
  only:
    refs:
      - main
      - dev
docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t "ansible" .
  cache:
    key: ${CI_COMMIT_BRANCH}
    paths:
      - "/var/lib/docker/"
  only:
    refs:
      - main
      - dev
.docker-push:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - cat version.txt > version
  after_script:
    - TAG=${TAG:-$(cat version)}
    - docker tag "ansible" "$CI_REGISTRY_IMAGE:$TAG"
    - docker push "$CI_REGISTRY_IMAGE:$TAG}"
  cache:
    key: ${CI_COMMIT_BRANCH}
    paths:
      - "/var/lib/docker/"
  only:
    - main
    - master

push_latest:
  extends: .docker-push
  stage: push
  variables:
    TAG: latest
  only:
    refs:
      - main
push_version:
  extends: .docker-push
  stage: push
  only:
    refs:
      - main
push_fullsemver:
  extends: .docker-push
  stage: push
  script:
    - cat fullSemVer.txt > version
  except:
    refs:
      - main

config:
  stage: config
  needs:
    - job: push_latest
      optional: true
  image: 
    name: $CI_REGISTRY_IMAGE:latest
    entrypoint: [""]
  script:
    - "echo hello"
...