version: '3.9'
services:
    ansible:
        image: custom-ansible
        build: 
            context: .
            dockerfile: ./ansible/dockerfile
        volumes:  
            - ./home/.ssh/:/root/.ssh/
            - ./ansible/:/root/ansible/
            - inventory:/root/ansible/inventory
            - ansible_home:/root/
    terraform:
        image: hashicorp/terraform
        environment:
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        user: root
        volumes:
            - ./home/:/root/
            - ./terraform:/root/terraform
        working_dir: /root/terraform/
        entrypoint: ["/root/entrypoint.sh"]
        command: ["terraform", "init"]
    packer:
        image: hashicorp/packer
        environment:
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        user: root
        volumes:
            - ./home/:/root/
            - ./packer:/root/packer
        working_dir: /root/packer/
        entrypoint: ["/root/entrypoint.sh"]
        command: ["packer","validate", "aws-ami.json"]
volumes:
    inventory:
    ansible_home: