version: '3.4'
services:
    ansible:
        image: custom-ansible
        build: 
            context: .
            dockerfile: ./ansible/dockerfile
        volumes: 
            - "./ansible/playbooks:/home/ansible/playbooks"
            - "./ansible/files/:/home/ansible/files/"
            - "./ansible/outputs:/home/ansible/outputs"
            - "./vars/:/home/ansible/vars/"
            - "./ansible/.ssh/:/home/ansible/.ssh/"
            - "./setup.sh:/home/ansible/setup.sh"
            - inventory:/home/ansible/inventory
            - ./ansible/host.csv:/home/ansible/host.csv
volumes:
    inventory: