version: '3.9'
services:
  ansible:
    extra_hosts:
      - "host-machine-1:$IP_HOST"
      - "host-machine-2:$IP_HOST"
    image: registry.gitlab.com/al3xdiaz/ansible:latest
    volumes:  
      - ~/container_home:/root/.ssh/
      - ~/.ssh/:/home/user_keys
      - ./:/root/ansible/
      - ansible_home:/root/
    command: ./ansible-test.sh
volumes:
  ansible_home: