version: '3.4'
services:
    ansible:
        environment:
            SERVER_HOST: ${SERVER_HOST}
            SERVER_USER: ${SERVER_USER}
            SERVER_NAME: ${SERVER_NAME}
            GIT_NAME: ${GIT_NAME}
            GIT_EMAIL: ${GIT_EMAIL}
            SSH_KEY_PASSPHRASE: ${SSH_KEY_PASSPHRASE}
        image: custom-ansible
        build: 
            context: .
            dockerfile: ./ansible/dockerfile
        volumes: 
            - "./ansible/playbooks:/home/ansible/playbooks"
            - "./ansible/files/:/home/ansible/files/"
            - "./ansible/outputs:/home/ansible/outputs"
            - "./vars/:/home/ansible/vars/"
            - "./ansible/ssh-keys/:/home/ansible/ssh-keys/"
            - "./setup.sh:/home/ansible/setup.sh"
            - inventory:/home/ansible/inventory
volumes:
    inventory: