version: '3.4'
services:
    ansible-service:
        container_name: ansible-service 
        image: custom-ansible
        build: 
            context: .
            dockerfile: ./ansible/dockerfile
        volumes: 
            - "./ansible/playbooks:/root/playbooks"
            - "./ansible/outputs:/root/outputs"
            - "./ansible/inventory:/root/inventory"
            - "./vars/:/root/vars/"
            - "./ansible/ssh-keys/:/root/ssh-keys/"