version: '3.9'
services:
  ansible:
    extra_hosts:
      - "host-machine-1:$IP_HOST"
      - "host-machine-2:$IP_HOST"
    image: gcr.io/al3xdiaz/ansible:latest
    build: 
      context: .
      dockerfile: ./dockerfile
    volumes:  
      - ~/container_home:/root/.ssh/
      - ~/.ssh/:/home/user_keys
      - ./:/root/ansible/
      - ansible_home:/root/
    command: ./ansible-test.sh
    tty: true
volumes:
  inventory:
  ansible_home: