---
- name: Main | desktop utils tools Aparence
  ansible.builtin.include_tasks: "01_aparence.yml"
- name: Main | desktop utils tools applications
  ansible.builtin.include_tasks: "02_applications.yml"
- name: Main | desktop utils tools applications
  ansible.builtin.include_tasks: "03_user_configuration.yml"
- name: Main | games
  ansible.builtin.include_tasks: "04_games.yml"
...
