#Desciption of the Ansible playbook
---
- name: install tools
  hosts: all
  become: true # true to become root

  tasks:
  - name: Simple install task htop
    when: ansible_os_family == "Debian"
    apt:
      name: htop
...
