# Desciption of the Ansible playbook
---
- name: install tools interpreters
  hosts: all
  become: true # true to become root
  gather_facts: no

  tasks:
  # update
  - name: "Update Repository cache"
    tags:
      - nodejs
      - python
      - golang
    apt:
      update_cache: true
      cache_valid_time: 3600
      force_apt_get: true
  - name: Add Node.js LTS
    tags:
      - nodejs
    shell: |
        curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
        apt install nodejs -y

  - name: Install reqired packages
    tags:
      - python
    apt:
      pkg:
        - git
        - curl
        - wget
  
  - name: "install golang"
    tags:
      - golang
    shell: |
      export GO_VERSION=$(curl -s https://go.dev/VERSION?m=text)
      wget https://dl.google.com/go/$GO_VERSION.linux-amd64.tar.gz
      tar xvf $GO_VERSION.linux-amd64.tar.gz -C /usr/local/
      rm $GO_VERSION.linux-amd64.tar.gz
  
  - name: "add go_path to path global"
    tags:
      - golang
    shell: |
        echo "#go path by user
        export GOPATH=\$HOME/go
        export GOBIN=\$GOPATH/bin
        export GOROOT=/usr/local/go
        export PATH=\$PATH:\$GOBIN:\$GOROOT/bin" >> /home/{{ hostvars[inventory_hostname].ansible_user }}/.bashrc