# Desciption of the Ansible playbook
---
- name: install tools interpreters
  hosts: all
  become: true # true to become root
  gather_facts: no

  tasks:
  # update
  - name: "Update Repository cache"
    tags:
      - nodejs
      - python
    apt:
      update_cache: true
      cache_valid_time: 3600
      force_apt_get: true
  - name: Add Node.js LTS
    tags:
      - nodejs
    shell: |
        curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
        apt install nodejs -y
  - name: Install reqired packages
    tags:
      - python
    apt:
      pkg:
        - git
        - curl
        - wget