# Desciption of the Ansible playbook
---
- name: install tools interpreters
  host: all
  become: true # true to become root

  tasks:
  # update
  - name: "Update Repository cache"
    tags:
      - nodejs
      - python
      - golang
    apt:
      update_cache: true
      cache_valid_time: 3600
      force_apt_get: true
  - name: Add Node.js LTS
    tags:
      - nodejs
    shell: |
        curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
        apt install nodejs -y

  - name: Install reqired packages
    tags:
      - python
    apt:
      pkg:
        - curl
        - wget
  
  - name: "install golang"
    tags:
      - golang
    shell: |
      rm -rf /usr/lib/go-1.6/ /usr/lib/go-1.6/src/ /usr/lib/go-1.6/src/runtime/ /usr/lib/go-1.6/src/runtime/race
      export GO_VERSION=$(curl -s https://go.dev/VERSION?m=text)
      wget https://dl.google.com/go/$GO_VERSION.linux-amd64.tar.gz
      tar xvf $GO_VERSION.linux-amd64.tar.gz -C /usr/local/
      rm $GO_VERSION.linux-amd64.tar.gz
  
  - name: "add go_path to path global"
    tags:
      - golang
    shell: |
        echo "#go path by user
        export GOPATH=\$HOME/go
        export GOBIN=\$GOPATH/bin
        export GOROOT=/usr/local/go
        export PATH=\$PATH:\$GOBIN:\$GOROOT/bin" >> /{{ hostvars[inventory_hostname].ansible_user }}/.bashrc