---
- name: Install tools
  hosts: all
  become: false

  tasks:
    - name: Add bullseye repository into sources list
      ansible.builtin.apt_repository:
        repo: deb http://ftp.de.debian.org/debian bullseye main non-free
        state: present
    - name: Install bluetooth components
      ansible.builtin.apt:
        pkg:
          - bluez-firmware
          - pulseaudio-module-bluetooth
          - pavucontrol
          - pavucontrol-qt
      when: ansible_os_family == "Debian"
      register: bluetooth
    - name: Restart pulse audio
      ansible.builtin.command: killall pulseaudio
      when: bluetooth.changed
