# Desciption of the Ansible playbook
---
- name: Install tools
  hosts: all
  become: true
  tasks:
    #dependences
    #mysql
    - name: Change mysql config
      when: ansible_os_family == "Debian"
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: ^(.*)(remount-ro.*)$
        line: \1remount-ro,barrier=0 0 1
        backrefs: true
      register: mysql_config

    - name: Reboot becouse mysql
      ansible.builtin.command: systemctl reboot
      when: lookup('env', 'DESKTOP_SESSION') != plasma
    - name: Reboot becouse mysql
      ansible.builtin.command: qdbus org.kde.ksmserver /KSMServer org.kde.KSMServerInterface.logout -1 1 1
      when: lookup('env', 'DESKTOP_SESSION') == plasma
