# Desciption of the Ansible playbook
---
- name: Install tools
  hosts: all
  become: true
  tasks:
    - name: Docker dependencies
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
      when:
        - ansible_os_family == "Debian"
    - name: Add Docker’s official GPG key
      ansible.builtin.shell: |
        rm -f /usr/share/keyrings/docker-archive-keyring.gpg
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        creates: /usr/bin/docker
      when:
        - ansible_os_family == "Debian"
    - name: Install docker Engine
      ansible.builtin.shell: |
        apt-get update
        apt-get install docker-ce docker-ce-cli containerd.io -y
      args:
        creates: /usr/bin/docker
      when:
        - ansible_os_family == "Debian"
    - name: Install docker compose
      when:
        - ansible_os_family == "Debian"
      tags:
        - docker-compose
      ansible.builtin.shell: |
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
        ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
        usermod -a -G docker $USER
      args:
        creates: /usr/bin/docker-compose
