---
- name: Install git
  apt:
    name: git
  when:
    - ansible_facts['distribution'] == "Debian"
- name: configure git
  tags: 
    - git
  shell: |
    git config --global user.email "{{ git_email }}"
    git config --global user.name "{{ git_name }}"
    git config --global user.signinkey {{ git_name }}
    git config --global gpg.program gpg
    git config --global pull.ff only
    git config --global init.defaultBranch main
    git config --global user.signinkey {{ git_email }}
      git config --global gpg.program gpg
  become: false
  become_user: "{{ ansible_user_id }}"
  when:
    - ansible_facts['distribution'] == "Debian"
- name: loop
  debug: 
    msg: "git email: {{ git_email }} git name: {{ git_name }}"
...