- name: Install git
  apt:
    name: git
- name: configure git
  tags: 
    - git
  shell: |
    git config --global user.email "{{ git_email }}"
    git config --global user.name "{{ git_name }}"
    git config --global pull.ff only